repos:
    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v2.32.2
        hooks:
              -   id: commitizen
                  name: CommitConvention
                  description: checking commits
                  stages: [ commit-msg ]
