repos:
    -   repo: https://github.com/commitizen-tools/commitizen
        rev: v2.32.2
        hooks:
            -   id: commitizen
                name: CommitConvention
                description: checking commits
                stages: [ commit-msg ]

    -   repo: local
        hooks:
            -   id: flake8
                name: flake8
                description: flake8 checks
                entry: flake8
                language: python
                types: [ python ]
                exclude: /(migrations)/
                args: [--config, setup.cfg]
